### ISSUE TITLE
Exception: can not find input device with 8 channel(s)

### ISSUE THREAD

**Issue by uchagani** [respeaker/mic_array#15]
I'm getting the following error running `python mic_array.py`.  Could be related to #14 

```
ALSA lib pcm_dsnoop.c:618:(snd_pcm_dsnoop_open) unable to open slave
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm_dsnoop.c:618:(snd_pcm_dsnoop_open) unable to open slave
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
(0, 'ReSpeaker Microphone Array: USB Audio (hw:0,0)', 0L, 2L)
(1, 'bcm2835 ALSA: - (hw:1,0)', 0L, 2L)
(2, 'bcm2835 ALSA: IEC958/HDMI (hw:1,1)', 0L, 2L)
(3, 'sysdefault', 0L, 128L)
(4, 'front', 0L, 2L)
(5, 'surround40', 0L, 2L)
(6, 'iec958', 0L, 2L)
(7, 'spdif', 0L, 2L)
(8, 'dmix', 0L, 2L)
(9, 'default', 0L, 128L)
Traceback (most recent call last):
  File "mic_array.py", line 190, in <module>
    test_8mic()
  File "mic_array.py", line 176, in test_8mic
    with MicArray(16000, 8, 16000 / 4)  as mic:
  File "mic_array.py", line 42, in __init__
    raise Exception('can not find input device with {} channel(s)'.format(self.channels))
Exception: can not find input device with 8 channel(s)
```

**Comment by uchagani** [comment]
Just FYI, I have the ReSpeaker Mic Array - Far-field w/ 7 PDM Microphones

**Comment by xiongyihui** [comment]
You should change the ReSpeaker Mic Array's firmware first. See 
See https://github.com/respeaker/mic_array#requirements

**Comment by uchagani** [comment]
I already did that (Linux) before I ran the script.

**Comment by xiongyihui** [comment]
But your log shows that the mic array only has 0 input channel

```
(0, 'ReSpeaker Microphone Array: USB Audio (hw:0,0)', 0L, 2L)
```

`0L, 2L` means 0 input channel (microphone) and 2 output channels

Maybe the firmware update failed, or other application was using the mic array.

**Comment by uchagani** [comment]
Another application possibly. I'll retry and stop the other application.
